openapi: 3.0.2
info:
  title: GobloG
  description: My first go project
  version: v1.0
servers:
  - url: /api/v1
components:
  schemas:
    Uuid:
      type: string
      format: uuid
    NonEmptyString:
      type: string
      minLength: 1
    Date:
      type: string
      format: data-time
    DateFromUser:
      type: string
      description: Default is the current date
      format: data-time
    PostSeed:
      type: object
      required:
        - authorName
        - content
      properties:
        postId:
          $ref: '#/components/schemas/Uuid'
        authorName:
          $ref: '#/components/schemas/NonEmptyString'
        content:
          $ref: '#/components/schemas/NonEmptyString'
        postedAt:
          $ref: '#/components/schemas/DateFromUser'
      additionalProperties: false
    Post:
      type: object
      required:
        - postId
        - authorName
        - content
        - postedAt
      properties:
        postId:
          $ref: '#/components/schemas/Uuid'
        authorName:
          $ref: '#/components/schemas/NonEmptyString'
        content:
          $ref: '#/components/schemas/NonEmptyString'
        postedAt:
          $ref: '#/components/schemas/Date'
      additionalProperties: false
    CommentSeed:
      type: object
      required:
        - postId
        - authorName
        - content
      properties:
        commentId:
          $ref: '#/components/schemas/Uuid'
        postId:
          $ref: '#/components/schemas/Uuid'
        authorName:
          $ref: '#/components/schemas/NonEmptyString'
        content:
          $ref: '#/components/schemas/NonEmptyString'
        commentedAt:
          $ref: '#/components/schemas/DateFromUser'
      additionalProperties: false
    Comment:
      type: object
      required:
        - commentId
        - postId
        - authorName
        - content
        - commentedAt
      properties:
        commentId:
          $ref: '#/components/schemas/Uuid'
        postId:
          $ref: '#/components/schemas/Uuid'
        authorName:
          $ref: '#/components/schemas/NonEmptyString'
        content:
          $ref: '#/components/schemas/NonEmptyString'
        commentedAt:
          $ref: '#/components/schemas/Date'
      additionalProperties: false
  responses:
    400:
      description: Client Error
paths:
  /posts:
    get:
      tags: ['posts']
      operationId: GetPosts
      responses:
        200:
          description: 'Successful list of posts'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      tags: ['posts']
      operationId: CreateOnePost
      requestBody:
        $ref: '#/components/schemas/PostSeed'
      responses:
        200:
          description: Successful list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        400:
          $ref: '#/components/responses/400'

